title: AD Knowledge Portal Metadata Dictionary
description: Explore AD Knowledge Portal metadata terms by key, value, or descriptions. 
theme: just-the-docs
logo: "VEOIBD Logo.png"
url: https://VEOIBD.github.io/data_models

aux_links:
  Data Curator App: https://dca.app.sagebionetworks.org/

callouts:
  highlight:
    color: yellow
  warning:
    title: WARNING
    color: red
  note: 
    color: purple
